/* var words = [
    'america',
    'animal',
    'apple',
    'bag',
    'barack obama',
    'basket',
    'bat',
    'boat',
    'box',
    'camera',
    'candle',
    'car',
    'cat',
    'china',
    'christmas',
    'clouds',
    'cobweb',
    'codepen',
    'coding',
    'computer',
    'cowboy',
    'cup',
    'denmark',
    'disney',
    'dog',
    'donald duck',
    'door',
    'drawing',
    'drums',
    'ears',
    'easter egg',
    'egg',
    'elon musk',
    'england',
    'europe',
    'eyes',
    'face',
    'facebook',
    'football',
    'fortnite',
    'france',
    'galaxy',
    'game',
    'germany',
    'google',
    'great britain',
    'guitar',
    'hacker',
    'hangman',
    'head',
    'headphones',
    'holiday',
    'horse',
    'house',
    'india',
    'italy',
    'jelly',
    'jigsaw',
    'kitchen',
    'lamp',
    'lemon',
    'letter',
    'light',
    'lightbulb',
    'mail',
    'mario',
    'melody',
    'mickey mouse',
    'microwave',
    'minecraft',
    'minigame',
    'mouse',
    'mouth',
    'movie',
    'music',
    'norway',
    'nose',
    'orange',
    'oxygen',
    'painting',
    'pants',
    'paper',
    'peace',
    'pen',
    'pencil',
    'pet',
    'pewdiepie',
    'piano',
    'plane',
    'poland',
    'present',
    'program',
    'programmer',
    'quiz',
    'radio',
    'remote control',
    'rocket',
    'russia',
    'school',
    'scotland',
    'screen',
    'seat',
    'shoes',
    'sky',
    'smartphone',
    'snake',
    'spaceship',
    'speakers',
    'star wars',
    'suitcase',
    'summer',
    'sun',
    'superhero',
    'sweater',
    'sweden',
    'television',
    'tools',
    'united states of america',
    'universe',
    'usain bolt',
    'vampire',
    'video',
    'village',
    'wales',
    'water bottle',
    'wind',
    'windmill',
    'window',
    'winter',
    'wizard',
    'word',
    'xylophone',
    'youtube',
    'zombie'
];
var hangman = [{
        from: [70, 38],
        to: [72, 46]
    },
    {
        from: [70, 38],
        to: [68, 46]
    },
    {
        from: [70, 45],
        to: [72, 55]
    },
    {
        from: [70, 45],
        to: [68, 55]
    },
    {
        from: [70, 35],
        to: [70, 45]
    },
    {
        circle: [70, 30],
        radius: 2
    },
    {
        from: [70, 5],
        to: [70, 25]
    },
    {
        from: [30, 5],
        to: [70, 5]
    },
    {
        from: [30, 95],
        to: [30, 5]
    },
    {
        from: [1, 95],
        to: [99, 95]
    }
];
// get stats
var stats = {
    streak: 0,
    scores: []
};
if (typeof (Storage) !== "undefined") {
    if (localStorage.hangman !== undefined) {
        stats = JSON.parse(localStorage.hangman);
        setScore();
    }
} */